<a href="https://colab.research.google.com/github/celeneheng/IS160Binder/blob/2/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#imported database from keras
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
from keras import models
from keras import layers
#models.Sequential() = layers within the model
network = models.Sequential()
#relu function accounts for overfitting
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
#used as last activation function of DL to normalize output
network.add(layers.Dense(10, activation='softmax'))


In [ ]:
#reshapes it into shape of model expectancy
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [ ]:
#trains the model by fitting model to training data
#chooses best parameter
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [ ]:
#prepares the label
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [ ]:
#fits the model to training data
#accuracy is 98.8
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 8s 15ms/step - loss: 0.2656 - accuracy: 0.9237
Epoch 2/5
469/469 [==============================] - 6s 12ms/step - loss: 0.1075 - accuracy: 0.9676
Epoch 3/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0715 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0519 - accuracy: 0.9840
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0386 - accuracy: 0.9884


In [ ]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

313/313 [==============================] - 1s 4ms/step - loss: 0.0818 - accuracy: 0.9749
test_acc: 0.9749000072479248


Our test data is 97.5 while our training data is 98.9, which indicates an overfitting issue

# MINST from **ChatGPT**

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical


In [ ]:
# Load and preprocess the dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)


11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
# Create the CNN model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))  # Output layer with 10 classes (digits 0-9)


In [ ]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
# Train the model
history = model.fit(train_images, train_labels, epochs=5, batch_size=64, validation_split=0.2)

# Evaluate the model on the test dataset
test_loss, test_accuracy = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_accuracy * 100:.2f}%')

Epoch 1/5
750/750 [==============================] - 42s 55ms/step - loss: 0.2159 - accuracy: 0.9336 - val_loss: 0.0778 - val_accuracy: 0.9774
Epoch 2/5
750/750 [==============================] - 43s 57ms/step - loss: 0.0596 - accuracy: 0.9818 - val_loss: 0.0480 - val_accuracy: 0.9859
Epoch 3/5
750/750 [==============================] - 39s 52ms/step - loss: 0.0423 - accuracy: 0.9866 - val_loss: 0.0480 - val_accuracy: 0.9846
Epoch 4/5
750/750 [==============================] - 38s 51ms/step - loss: 0.0317 - accuracy: 0.9894 - val_loss: 0.0366 - val_accuracy: 0.9893
Epoch 5/5
313/313 [==============================] - 2s 8ms/step - loss: 0.0419 - accuracy: 0.9877
Test accuracy: 98.77%


This indicates that the training process has completed five epochs.The loss value (0.0256) is a measure of how well the neural network is performing on the training dataset. Lower values indicate better performance. An accuracy of 0.9919 means that the network is correctly classifying approximately 99.19% of the training data. A validation loss of 0.0492 is relatively low, indicating good generalization. An accuracy of 0.9853 means that the network is correctly classifying approximately 98.53% of the validation data.